### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by gaeldemarseille** [kodosexe/F1Hub#5]
I'm on Windows 10, here's the output for python3 main.py

```
Traceback (most recent call last):
  File "C:\Users\Gael\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\simple_term_menu.py", line 36, in <module>
    import termios
ModuleNotFoundError: No module named 'termios'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Gael\f1hub\f1hub\main.py", line 4, in <module>
    from simple_term_menu import TerminalMenu
  File "C:\Users\Gael\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\simple_term_menu.py", line 38, in <module>
    raise NotImplementedError('"{}" is currently not supported.'.format(platform.system())) from e
NotImplementedError: "Windows" is currently not supported.
```

**Comment by kodosexe** [comment]
Windows is not supported by the menu dependency.
You will need to use Windows Subsystem for Linux:
https://docs.microsoft.com/learn/modules/get-started-with-windows-subsystem-for-linux/

I have plans to move to a different dependency in the future

**Comment by gaeldemarseille** [comment]
Ok, readme isn't clear about that

**Comment by kodosexe** [comment]
Yeah, I just figured it out myself, I'll add it soon
